Revert "dlkm: Create kernel_headers module qti_kernel_headers"
This reverts commit c7dcf4fc8691beb3ad9b446532fc9cb12ea7797b.

Reason for revert: Breaks existing targets with
error: kernel/msm-4.14/Android.bp:30:1: module "qti_kernel_headers" already defined
device/qcom/common/dlkm/Android.bp:1:1 <-- previous definition here

Change-Id: I857071fe582958c2ff1f68544e2acca2fc257084